version: '3.1'

services:
  db:
    image: postgres:16.0
    environment:
      POSTGRES_DB: crocobet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
